name: main
on: [push]
jobs:
  check-npm:
    runs-on: ubuntu-latest
    env:
      DROPBOX_APP_NAME: ${{ secrets.APP_NAME }}
      SOME_ENV: "not secret env"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: echo $SOME_ENV
      - name: Send file to dropbox
        run: node actions.js && echo "SUCCESSFUL"
        env:
          CI: true
          DROPBOX_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}